### ISSUE TITLE
servere error

### ISSUE THREAD

**Issue by GizliBaskan** [Tuke-Nuke/TuSKe#100]
I am using tuske in its latest version.
Server version: Tuinity 1.16.5
but I am getting this error. Can you help me?

Also tuske stops working when viaversion 4.0.0 is updated. Can you take a look at this too?
https://paste.turingarch.com/paste.php?id=128

**Comment by Gerbenv21** [comment]
same problem but on 1.17.1, any solutions?

**Comment by JustSkeppYT** [comment]
TuSke doesn't work on 1.11+

It's recommended to use alternatives such as skript-gui, it's simple and usually within 15 days you're help is resolved.
skript-gui https://github.com/APickledWalrus/skript-gui
