### ISSUE TITLE
Issue with tuske (1.16.5)

### ISSUE THREAD

**Issue by Elias-0001** [Tuke-Nuke/TuSKe#103]
Hello, I have an issue with tuske at my 1.16.5 minecraft server. I'm using the newest version of tuske and skript. Help. :(

**Comment by JustSkeppYT** [comment]
TuSke doesn't work for 1.16.5

**Comment by JustSkeppYT** [comment]
TuSke doesn't work on 1.11+

It's recommended to use alternatives such as skript-gui, it's simple and usually within 15 days you're help is resolved.
skript-gui https://github.com/APickledWalrus/skript-gui
