### ISSUE TITLE
GUI Doesn't Want To Work

### ISSUE THREAD

**Issue by MrcsM** [Tuke-Nuke/TuSKe#25]
When I switched from SkQuery to TuSKe GUIs, my skript said it loaded in game, but in console it gave me an error and now I can't do the command with the gui stuff in it. Any fixes?

Error: https://pastebin.com/raw/28FesGDg

**Comment by Pikachu920** [comment]
This seems to be a issue with another add-on registering something to do with "animation". try disabling that.
