### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by bloggy** [Tuke-Nuke/TuSKe#26]
https://hastebin.com/fedoninohe.vbs

Latest TuSke version.

Any ideas?

I am on 1.12.2 PaperSpigot.

**Comment by Pugabyte** [comment]
Add `with permission %string%` at the end of any gui lines that make the player run a command. This is a problem with the latest commit and will probably be fixed soon

**Comment by Pikachu920** [comment]
I will attempt to fix this

**Comment by Pikachu920** [comment]
can you provide a script that makes the error come up? I can't get it to show.

**Comment by bloggy** [comment]
Here is a script:

`command /guitest:
	trigger:
		skellett open "CHEST" with 3 rows named "&6TEST" to player
		make a gui slot 1 of player with hopper with name "&4TEST" with lore "TEST" to close then run player command "/help"`

You must not be OP or have admin permissions. You then just click on the button in the gui and you will see the error in console. Latest TuSke version, and I am on PaperSpigot (1.12.2) and Bensku Skript (latest).

**Comment by Pikachu920** [comment]
[Here](https://drive.google.com/file/d/1nEXrlY_zFxd8a_d3tqrFBIxSZ2Qm5jZj/view) is a patched version of TuSKe 1.8.2 with this bug fixed. I've also opened a PR (#29) to address this.

**Comment by bloggy** [comment]
I have tested it with the skript I gave you. And it works now! No errors. Thanks a lot for the effort and the hotfix!
