### ISSUE TITLE
Slow load/reload.

### ISSUE THREAD

**Issue by UzumakiYT** [Tuke-Nuke/TuSKe#28]
using:
create a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 49, 50, 51, 52 and 53 of player with diamond_sword named "&7" with lore "&7" to do nothing	

will make the skript to load more harder.

- not really important.

**Comment by epicskymi** [comment]
use make instead of create its a known issue it causes lag

**Comment by UzumakiYT** [comment]
now works fine and faster, thanks
