### ISSUE TITLE
'GUI' can't be used when creating a gui

### ISSUE THREAD

**Issue by HYPExMon5ter** [Tuke-Nuke/TuSKe#34]
Error: ![image](https://user-images.githubusercontent.com/12315186/34457545-a6f285ec-ed81-11e7-8c78-24e6c6fe1993.png)

Code:
```
command /bug:
	trigger:
		create a gui with virtual chest with 2 rows named "TuSKe Bug":
			make gui slot 1, 3, 10, 11, 12, 19, 28, 36, 37, 45, 46, 52 and 53 with black stained glass pane named "&0"
			if slot 1 of gui is dirt:
				make gui slot 1 with grass
			else:
				make gui slot 1 with diamond block
		open last created gui to player
```

**Comment by Blueyescat** [comment]
Just read the error message, you can't use ``gui`` outside of ``make gui``.
```vb
make gui slot 1, 3, 10, 11, 12, 19, 28, 36, 37, 45, 46, 52 and 53 with black stained glass pane named "&0":
	if slot 1 of gui is dirt:
		make gui slot 1 with grass
	else:
		make gui slot 1 with diamond block
```

**Comment by HYPExMon5ter** [comment]
I did, I was asked by tuke to make an issue though

**Comment by Blueyescat** [comment]
I can't see purpose on using ``gui`` in ``create gui`` code block.

**Comment by HYPExMon5ter** [comment]
to get the inventory of the gui you're creating??

**Comment by Blueyescat** [comment]
Why you wou want that lol. But did you try to use ``gui "id"`` or ``last gui``?

**Comment by HYPExMon5ter** [comment]
making a slot stealable without having to have on `on inventory open` or conditionals, like i provided in the code above, etc., there are quite a few uses. and I'm not gonna create a gui with a id if it's not gonna stay the same or close to it, there's no point.

**Comment by Blueyescat** [comment]
You can use ``last gui`` already. Also as i remember you can use
```vb
make gui ...:
    uncancel event
```
to get stealable items.

**Comment by HYPExMon5ter** [comment]
that'd make all items stealable, i want specific items stealable.

**Comment by Blueyescat** [comment]
No it shouldn't do that. The manager cancels inventory click event when you click on a gui item, this uncancels it.

**Comment by HYPExMon5ter** [comment]
oh i see what you're saying. Like
```
make gui slot 1 with grass:
    uncancel event
```
? that way only the grass would be stealable?

**Comment by Blueyescat** [comment]
Yeah. The code in the ``make gui`` section runs on ``inventory click`` event.

**Comment by HYPExMon5ter** [comment]
Anyways, I only posted this cause I was asked by tuke to do so lol

**Comment by Blueyescat** [comment]
``[the] gui`` support may look better than ``last gui``. Since `last gui` in `create gui` works it is easy to do. But still i can't see advantages :stuck_out_tongue:

**Comment by Tuke-Nuke** [comment]
I tested it and I can't replicate your issue. The `gui` expression is used when you click in a gui slot, if it's outside of `make gui` effect like your example, the right one is `last gui`. It might be just a syntax mistake where the syntax `last [created] gui` represents the current gui that is being created/edited.
So your code will work fine as:
```vbs
command /bug:
	trigger:
		create a gui with virtual chest with 2 rows named "TuSKe Bug":
			make gui slot 1, 3, 10, 11, 12, 19, 28, 36, 37, 45, 46, 52 and 53 with black stained glass pane named "&0"
			if slot 1 of last gui is dirt:
				make gui slot 1 with grass
			else:
				make gui slot 1 with diamond block
		open last created gui to player
```

**Comment by HYPExMon5ter** [comment]
Oh okay, thanks :)
