### ISSUE TITLE
Custom name in recipe not work

### ISSUE THREAD

**Issue by Spartan9802** [Tuke-Nuke/TuSKe#45]
Hi,
I've just realized that custom recipe items don't work anymore, I have no error my skript version is dev-25, I also tested with dev-32...

**Comment by ShaneBolenback** [comment]
Im having the same issue, I created 1 item (custom1) and then I'm trying to use that item in recipe for (custom2) .... but its not working, custom1 is a poisonous potato with a name and lore, but the recipe allows you to use a regular poisonous potato, kind of defeats the purpose.
