### ISSUE TITLE
set variable to all items of gui-inventory not working

### ISSUE THREAD

**Issue by melinstagibson** [Tuke-Nuke/TuSKe#47]
So this is weird bug:
Im trying to do this to create kits:

```
command /editkit <string>:
        permission: mel.createkit
        trigger:
                if gui "%arg-1%" is set:
                        open gui "%arg-1%" to player
                else:
                        create gui "%arg-1%" with virtual chest named "&2Edit Kit ""&a&l%arg-1%&2""":
                                run when close the gui:
                                        set {kit::%arg-1%::*} to all items of gui-inventory
                        open last created gui to player
```
But it doesnt seem to work (variable isnt being set) if i use %arg-1% in the variable name.
if i, instead, do it like this:
```
set {kit::test::*} to all items of gui-inventory
```
it works

I tried it without gui-inventory to see if its a skript issue but this:
```
command /testkit <string>:
    permission: *
    trigger:
        set {kit::%arg-1%::*} to all items in player's inventory
```
works aswell so its a TuSke issue

**Comment by melinstagibson** [comment]
Edit:
the arg-1 isn't carried over to the run when close part of the skript it seems, doing this:
```
command /editkit <string>:
        permission: mel.createkit
        trigger:
                set {arg-1} to arg-1
                if gui "%arg-1%" is set:
                        open gui "%arg-1%" to player
                else:
                        create gui "%arg-1%" with virtual chest named "&2Edit Kit ""&a&l%arg-1%&2""":
                                run when close the gui:
                                        set {kit::%{arg-1}%::*} to all items of gui-inventory
                        open last created gui to player
```
works as workaround
(i set arg-1 to a varioable {arg-1} and used that instead)

**Comment by Blueyescat** [comment]
Already you have to do that with the current system. You should read the wiki 🙂

https://github.com/Tuke-Nuke/TuSKe/wiki/GUI-Manager#things-you-need-to-know
![image](https://user-images.githubusercontent.com/19474570/36351161-8944696e-14b6-11e8-8111-985a68c22ed1.png)

So you should close this issue.

**Comment by melinstagibson** [comment]
Weird, last time i tried it didnt work with temporary variables either but ill try again, thanks.
