### ISSUE TITLE
Advanced Gui ?

### ISSUE THREAD

**Issue by weberlepecheur** [Tuke-Nuke/TuSKe#5]
Hello,

I would like to know if the advanced gui works?
If so, I entered the same line as you but nothing appears on the screen.

```php
command /test:
	trigger:
		# virtual %inventorytype% [inventory] [with size %-number%] [(named|with (name|title)) %-string%]
		create a new gui with virtual chest inventory with size 1 named "Test"
		
command /test2:
	trigger:
		#syntax: create [a] [new] gui [[with id] %-string%] with %inventory% [and shape %-strings%]
		create a gui with virtual chest with 6 rows named "&4Select the server"
```

> [18:18:58] [Server thread/INFO]: WeBer_Le_Pecheur issued server command: /test
> [18:18:58] [Server thread/INFO]: WeBer_Le_Pecheur [fe8906fa-41f5-42f7-b0f1-4762796b9e49]: /test
> [18:18:58] [Server thread/INFO]: [Skript] # /test 
> [18:18:58] [Server thread/INFO]: [Skript] command /test (simple event)
> [18:18:58] [Server thread/INFO]: [Skript]   create gui
> [18:18:58] [Server thread/INFO]: [Skript] # test took 0.373272 milliseconds

Also I would like to point out that in the documentation, it is written "left mouse butto**m**" instead of "left mouse butto**n**"

Spigot 1.11.2 (git-Spigot-3fb9445-2b6c9f4)
Skript-dev28c
TuSKe 1.7.7-beta

**Comment by Syst3ms** [comment]
You need to open the gui after having created it using `open last gui to player`

**Comment by weberlepecheur** [comment]
Oh ok, I'll try later I thought it worked like the previous version

**Comment by Syst3ms** [comment]
Yeah, the system is a bit different. Make sure to close this issue if it works.
