### ISSUE TITLE
Console startup error

### ISSUE THREAD

**Issue by bloggy** [Tuke-Nuke/TuSKe#55]
Console error on startup:
https://hastebin.com/inixutinap.sql

Using bensku's fork (latest available version)

**Comment by HYPExMon5ter** [comment]
Use this to fix it https://cdn.discordapp.com/attachments/399406334526750723/440604232874197002/TuSKe-PikachuPatch-v2.jar

also, look at the issues before reporting new ones, there's already 2 of these open.
