### ISSUE TITLE
Make Drop effect doesn't work

### ISSUE THREAD

**Issue by nutella25** [Tuke-Nuke/TuSKe#6]
Due to latest update, I tried to do some simple script like this:
```
on right click with fishing rod:
	add 1 to {fish.%player%}
	if {fish.%player%} is not set:
		set {fish.%player%} to 1
	if {fish.%player%} >= 20:
		chance of 65%:
			make player drops 1 of held item from his inventory
			set {fish.%player%} to 0
			message "&6Pancinganmu terlepas dari tangan!"
			stop
		set {fish.%player%} to 0
```
and it doesn't drop anything

**Comment by Tuke-Nuke** [comment]
Try to change to `make player drops 1 of held item from held item`

**Comment by nutella25** [comment]
Already do that, but still not working. It seems working like a `stop effect` which the `{fish.%player%}` not set to 0 and won't message the `"&6Pancinganmu terlepas dari tangan!"`

**Comment by Tuke-Nuke** [comment]
Just to remember. What is your server and TuSKe version?

**Comment by Tuke-Nuke** [comment]
Do you still have the issue? Even with `1.7.7-beta`?

**Comment by Tuke-Nuke** [comment]
Closed due to inactivity and I can't reproduce it + it's working fine in latest versions.
