### ISSUE TITLE
Custom Enchantments

### ISSUE THREAD

**Issue by ShaneBeee** [Tuke-Nuke/TuSKe#60]
Hey, not sure if this add-on is still maintained but figured i'd try posting here anyways.
2 Things about custom enchantments

#1 - I have made a few custom enchantments according to your guide, and it all works fine and dandy, except they never show up in my enchanting table. I have set rarities to high (5), everything is showing up in my config file all fine, but still no enchants in the table. I have tried with MANY chestplates, boots, even books, and not once did a custom enchant show up. I have restarted the server several times and still nothing. If I use the command /tuske each give, it applies to the item, but not showing up in the table.

#2 - I just wanted to suggest removing the "unbreaking" that it adds to every tool. Im assuming that is added to give the item the glowing effect, but I know you can give the item the glowing effect WITHOUT having to enchant it. 

Thanks for reading!

**Comment by K3nni** [comment]
my custom enchantments also don't work over the enchantment table ..  That's pretty dumb.

**Comment by SekoiaTree** [comment]
Adding a comment to bring this back to light... still doesn't work in 2020

**Comment by ShaneBeee** [comment]
Im closing this issue as Tuke-Nuke hasn't maintained Tuske in a few years now.
I believe when I created this issue I wasn't aware he dropped support.
