### ISSUE TITLE
to run: in gm 3 doesn't work

### ISSUE THREAD

**Issue by uiytt** [Tuke-Nuke/TuSKe#61]
Serveur : 1.12.2
Skript : dev35b (36)
Tuske : TuSKe 1.8.3-PikachuPatch-v2 (i also tested with 1.8.2)
When a player is in gm 3 and clicks on an item, the code under the to run: doesn't work

**Comment by Matocolotoe** [comment]
oh un français de skript-mc xd
essaie de mettre le code dont tu es sûr que certains joueurs pourront l'exécuter en gm 3 dans un `on inventory click:`
_try to put the code for which you are sure that some players will be able to execute this in gm 3 ina n `on inventory click:`_

**Comment by uiytt** [comment]
xD
And okay thanks
