### ISSUE TITLE
advanced GUI broke in dev36

### ISSUE THREAD

**Issue by signition** [Tuke-Nuke/TuSKe#62]
```
command /testGUI:
	trigger:
		create a gui with virtual chest with 1 rows named "&ftestGUI":
			make gui 0 with stone named "&ftestName" with lore "&ftestLore"
		open last gui to player
```
This should make menu at inventory 0 ( first one ) with stone named "&ftestName" and lore "&ftestLore" , yet it doesn't work properly in dev35 and dev36. It works fine with dev31c. 

The error message is this.
```
 can't understand this condition: 'make gui ...
```

**Comment by Padlick** [comment]
This isn't Skript or TuSKe's Issue. You have a fail in your syntax.
Use:
make gui slot 0 with stone named "&ftestName" with lore "&ftestLore"

This works just fine, also in Skript dev36 (not dev37; GUI Manager completly broken in dev37)
