### ISSUE TITLE
Events: on anvil not working 1.12

### ISSUE THREAD

**Issue by YellowZaki** [Tuke-Nuke/TuSKe#7]
I know you are fixing 1.12 bugs. I you didn't know, anvil events don't work on 1.12.

**Comment by Tuke-Nuke** [comment]
Thank's for reporting but could you give some details? Does it shows some console error? did you updated TuSKe when changing to 1.12?

**Comment by YellowZaki** [comment]
Any console error. It is the first time I use 1.12, I don't know if it used to work with 1.11.


on anvil combine:
    message "hey" to player


When I combine items, it doesn't message me.
Skript doesn't send any error when I reload, so it recognizes the event.

**Comment by Tuke-Nuke** [comment]
What is your TuSKe and Skript version? It is working nice in TuSKe v1.7.7-beta and Skript dev29.

**Comment by YellowZaki** [comment]
TuSke 1.7.7
Skript dev29

I'll try the beta, thanks!

**Comment by Tuke-Nuke** [comment]
Closing since it is solved.
