### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by ghost** [Tuke-Nuke/TuSKe#73]
Hey. Im using TuSKe on 1.12.2 but i have a error everytime i want to open my gui:
An internal error occurred while attempting to perform this command, The GUI opens but the Items that should be in the gui are not loaded and i get a error in the console:
https://pastebin.com/XsDG7961

This is my code:
command /staffsoli:
	trigger:
		open chest with 5 rows named "&6Staff Sollicitaties" to player
		set {_s} to 0
		format gui slot 36 of player with Book and quill named "&6Maak Sollicitatie" to close:
			set {_book} to new written book
			open book {_book} to {_p}
			set page 1 in book {_book} to "&7Type je Sollicitatie hier onder!"

Can someone help me ?

**Comment by Spoorloos** [comment]
Sorry for my bad English i'm dutch

**Comment by Blueyescat** [comment]
Use @Pikachu920's fork of TuSKe: https://github.com/Pikachu920/TuSKe/releases

**Comment by Spoorloos** [comment]
I already tried that but it didn't work :(
