### ISSUE TITLE
Major Tuske bug

### ISSUE THREAD

**Issue by tinesone** [Tuke-Nuke/TuSKe#92]
I tried to create a new GUI (as one does with TUSKE) and this is the error that i got:

java.lang.NullPointerException: null                                                                                            at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:146) ~[?:?]                                 at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]                           at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]                                                                                                                   at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]                                                                                         at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]                                                                                                                    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]                                                                                                                     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]                                                                                                                     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]                                                                                                                   at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]                                                           [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! [Skript] Severe Error:                                                           [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.                                       [13:31:43] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.        [13:31:43] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons). [13:31:43] [Server thread/ERROR]: #!#! Here is full list of them:                                                       [13:31:43] [Server thread/ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) SkBee MundoSK (https://forums.skunity.com/resources/mundosk.69/) SkQuery Skellett (https://forums.skunity.com/resources/skellett.24/)                                 [13:31:43] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.                                                                                                          [13:31:43] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.                                                                                                                   [13:31:43] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.                                                                                                     [13:31:43] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.         [13:31:43] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.                                                                                               [13:31:43] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.      [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! Stack trace:                                                                     [13:31:43] [Server thread/ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0                                      [13:31:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.getParameter(Function.java:66)      [13:31:43] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.util.EvalFunction.getParemetersValues(EvalFunction.java:85)                                                                                                             [13:31:43] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:135)                                                                                                                [13:31:43] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54) [13:31:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)                      [13:31:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)                 [13:31:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)                 [13:31:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)                      [13:31:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)      [13:31:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)  [13:31:43] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)                                                                                                                        [13:31:43] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)                                                                                                                     [13:31:43] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)                                                                                                                     [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1828)                                                                                                                      [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68)      [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13)      [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)                                                                                                       [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)                 [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)                                                                                                                       [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)                                                                                                               [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)                                                                                                                       [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)                                                                                                                        [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)                                                                                                               [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)                                                                                                                        [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)                                                                                                              [13:31:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)                                                                                                                       [13:31:43] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)                                      [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! Version Information:                                                             [13:31:43] [Server thread/ERROR]: #!#!   Skript: 2.4.1 (latest)                                                         [13:31:43] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github                                                    [13:31:43] [Server thread/ERROR]: #!#!     Date: 2019-12-22                                                             [13:31:43] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT                                                   [13:31:43] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2                                                              [13:31:43] [Server thread/ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08)                 [13:31:43] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0                                                      [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! Server platform: Spigot                                                          [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! Current node: null                                                               [13:31:43] [Server thread/ERROR]: #!#! Current item: format a gui slot [[long:1]] of the player with ([[itemtype:bow]] named "ºrSkeleton Archer" with lore ("ºrº7Ranged class" and "ºrº2ºoUndead")[class java.lang.String] >> ch.njol.skript.classes.data.DefaultConverters$13@503408d2: itemtype -> itemstack)                                                         [13:31:43] [Server thread/ERROR]: #!#! Current trigger: right click on villager (rightclick on [[entitydata:villager]]) (shop.sk, line 1)                                                                                                       [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! Thread: Server thread                                                            [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! Language: english                                                                [13:31:43] [Server thread/ERROR]: #!#! Link parse mode: DISABLED                                                        [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:31:43] [Server thread/ERROR]: #!#! End of Error.                                                                    [13:31:43] [Server thread/ERROR]: #!#!                                                                                  [13:34:52] [Dynmap Render Thread/INFO]: [dynmap] Loading default resource pack                                          [13:34:57] [Server thread/WARN]: [Skellett] Loaded class org.json.JSONObject from SkQuery v3.6.5 which is not a depend, softdepend or loadbefore of this plugin.                                                                                [13:36:23] [Server thread/INFO]: tinesone [5b7a57c2-23e9-4cd5-a89a-18800fff3545]: /start                                [13:36:23] [Server thread/INFO]: [MundoSK] An exception has occured within MundoSK                                      [13:36:23] [Server thread/INFO]: [MundoSK] Please report this to the MundoSK page on forums.skunity.com                 [13:36:23] [Server thread/INFO]: [MundoSK] Bukkit/Spigot version: git-Spigot-a99063f-c9d7c16 (MC: 1.15.2)               [13:36:23] [Server thread/INFO]: [MundoSK] Skript version: 2.4.1                                                        [13:36:23] [Server thread/INFO]: [MundoSK] MundoSK version: 1.8.6-BETA.58                                               [13:36:23] [Server thread/INFO]: [MundoSK] Exception at ProfileManager                                                  [13:36:23] [Server thread/WARN]: java.lang.NullPointerException                                                         [13:36:23] [Server thread/WARN]:        at com.pie.tlatoani.Skin.ProfileManager.respawnPlayer(ProfileManager.java:249)  [13:36:23] [Server thread/WARN]:        at com.pie.tlatoani.Skin.ProfileManager.refreshPlayer(ProfileManager.java:224)  [13:36:23] [Server thread/WARN]:        at com.pie.tlatoani.Skin.ModifiableProfile$Specific.changeDisplayedSkin(ModifiableProfile.java:141)                                                                                                     [13:36:23] [Server thread/WARN]:        at com.pie.tlatoani.Skin.ModifiableProfile$Specific.access$300(ModifiableProfile.java:128)                                                                                                              [13:36:23] [Server thread/WARN]:        at com.pie.tlatoani.Skin.ModifiableProfile.lambda$consistentlySetDisplayedSkin$6(ModifiableProfile.java:104)                                                                                            [13:36:23] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)           [13:36:23] [Server thread/WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)                [13:36:23] [Server thread/WARN]:        at java.util.Iterator.forEachRemaining(Unknown Source)                          [13:36:23] [Server thread/WARN]:        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)  [13:36:23] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)                   [13:36:23] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)            [13:36:23] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)     [13:36:23] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)                                                                                                                       [13:36:23] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)                   [13:36:23] [Server thread/WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)                   [13:36:23] [Server thread/WARN]:        at com.pie.tlatoani.Skin.ModifiableProfile.consistentlySetDisplayedSkin(ModifiableProfile.java:102)                                                                                                     [13:36:23] [Server thread/WARN]:        at com.pie.tlatoani.Skin.ExprDisplayedSkinOfPlayer.change(ExprDisplayedSkinOfPlayer.java:108)                                                                                                           [13:36:23] [Server thread/WARN]:        at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)                 [13:36:23] [Server thread/WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:52)                               [13:36:23] [Server thread/WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)                    [13:36:23] [Server thread/WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)                    [13:36:23] [Server thread/WARN]:        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)                         [13:36:23] [Server thread/WARN]:        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)        [13:36:23] [Server thread/WARN]:        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)         [13:36:23] [Server thread/WARN]:        at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)             [13:36:23] [Server thread/WARN]:        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)         [13:36:23] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                  [13:36:23] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)                  [13:36:23] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)              [13:36:23] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)                              [13:36:23] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) [13:36:23] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)   [13:36:23] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)                                                                                                                        [13:36:23] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)                                                                                                                        [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1650)                                                                                                             [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)   [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)    [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)                                                                                                          [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)                    [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)  [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)                                                                                                                  [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)  [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)   [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)                                                                                                                  [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)   [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)                                                                                                                 [13:36:23] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)  [13:36:23] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)  

Now the really weird thing is, i have more then one GUI and the other ones work fine. I just can't create any more. I have not update skript nor tuske (tho after getting this error, i did update to the later version of 1.8.3-pikachuPatchv3)

Code that doesn't work:
`on right click on villager:
  cancel event
  open virtual chest with size 3 named "&2Shop" to player
  format gui slot 0 of player with iron sword named "&2Upgrade sword" to close then run function upgradeSword()`

`function upgradeSword():
  send "yeet" to all players`

code that works:
`on right click on ender chest:
  cancel event
  if {started} is false:
    play sound "block.enchantment_table.use" to player
    open virtual chest inventory with size 3 named "&4Choose class!" to player
    format gui slot 0 of player with iron sword named "&rDark Knight" with lore "&r&7Tanky Melee class" and "&r&8&oHuman" to close then run function firstDarkKnight(player)
    format gui slot 1 of player with bow named "&rSkeleton Archer" with lore "&r&7Ranged class" and "&r&2&oUndead" to close then run function firstArcherSkeleton(player)
  else:
    make player execute "/shop"`

`#Dark knight class
function firstDarkKnight(player: player):
  clear {_player}'s inventory
  set gamemode of {_player} to spectator
  darkKnight({_player})
  start()`

`function darkKnight(player: player):
  execute console command "lp user %{_player}% parent set darkknight"
  if {attackArmorUpgrade} is 0:
    equip {_player} with chainmail leggings of curse of binding 1 with nbt "{Unbreakable:1}"
    equip {_player} with chainmail chestplate of curse of binding 1 with nbt "{Unbreakable:1}"
  if {attackHelmetUpgrade} is bigger than 0:
    equip {_player} with {attackHelmet}
  equip {_player} with {attackBoots}
  if {attackHealthUpgrade} is 0:
    apply health boost without any particles to {_player} for 999 days
  set slot 0 of {_player} to {attackSword}`

**Comment by JackTMR** [comment]
The Skript addon is old, it doesn't get updated and therefore won't do very well.

I don't think there is anything to stop this bug happening.
