### ISSUE TITLE
arg-1 is <none>

### ISSUE THREAD

**Issue by Skiuel** [Tuke-Nuke/TuSKe#97]
`command /example <string>:
	trigger:
		open virtual chest inventory with size 1 named "example" to player
		format gui slot 1 of player with feather named "example" to run:
			send "Example %arg-1%"
			close player's inventory`

If I execute `/example SomeText` it's give `Example <none>`

**Comment by Matocolotoe** [comment]
You gotta set a local variable to `arg-1` before the section below `to run:` and then use it instead
