### ISSUE TITLE
Skript can't load commands and triggers with TuSKe

### ISSUE THREAD

**Issue by AZERTY442005** [Tuke-Nuke/TuSKe#98]
Hi, 2 days ago, i updated TuSKe, but when i reloaded my scripts, Skript said, "6 scripts, 0 triggers, 0 commands", so i tryed to remove each Skript addons and i found TuSKE.
So i need help because, i removed it and "6 scripts, 32 triggers, 20 commands, but 87 errors: can't understand "cancel drops". So im stuck until next update. Please if someone can help me, pls, do it tysm

![image](https://user-images.githubusercontent.com/73392042/121397403-30e5dc00-c94c-11eb-845c-55a7766f7f24.png)

**Comment by iOshawott** [comment]
Use skript-gui, there will not be any updates.

**Comment by AZERTY442005** [comment]
Ok ty for replying me, but i need to use "cancel drops", can you help me?
