### ISSUE TITLE
Netherite sword does not register in TuSKe's GUI

### ISSUE THREAD

**Issue by agentgamer100** [Tuke-Nuke/TuSKe#99]
I might be dumb but...

For some reason TuSKe's gui doesnt allow netherite swords to be in the gui. Ive tried a bunch of things here but it doesnt work. My TuSKe version is 1.8.2-pikachu-patch and 1.16.4 minecraft
Here is my skript:

`on right click on player:
	if event-entity's display name is "Store":
		send "&aOpening Store..." to player
		create new gui with virtual chest named "Shop" with 3 rows:
			format gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, and 27 with gray stained glass pane named "&a"
			format gui slot 11 with diamond sword named "&b&lMelee Weapons":
				MeleeShop(player)
		open last gui to player

function MeleeShop(p: player):
	set {_u} to uuid of {_p}
	create new gui with virtual chest named "Melee Shop" with 3 rows:
		format gui slot 15 with netherite sword named "<##ffa600>Dragon Sword" with lore "<##ff6900>Created by the breath of a", "<##ff6900>dragon, this great sword is only", "<##ff6900>for the most serious..." and "&6Price &e&l| &r&610000 Coins":
			if {Money::%{_p}%} is greater than or equal to 10000:
				give {_p} netherite sword named "<##ffa600>Dragon Sword" with lore "<##ff6900>Created by the breath of a", "<##ff6900>dragon, this great sword is only" and "<##ff6900>for the most serious..."
				remove 10000 from {Money::%{_p}%}
				send "&aSuccess!" to {_p}
			else:
				send "&cNot enough coins!" to {_p}
	open last gui to {_p}`

Also, i can click the slot and it gives me the item, but it doesnt appear in the GUI

**### EDIT: This also happens with crossbows**

**Comment by iOshawott** [comment]
It's outdated. You should use skript-gui instead. There will be no patch for it.
